BEGIN;

CREATE TABLE IF NOT EXISTS roles (
  id BIGINT PRIMARY KEY,
  name VARCHAR(64) NOT NULL UNIQUE,
  description TEXT
);

CREATE TABLE IF NOT EXISTS users (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  username VARCHAR(255) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  full_name VARCHAR(255) NOT NULL DEFAULT '',
  manager VARCHAR(255),
  supervisor VARCHAR(255),
  cpf VARCHAR(32),
  branch VARCHAR(64),
  email VARCHAR(255),
  phone VARCHAR(20),
  role VARCHAR(64) NOT NULL DEFAULT 'operador',
  is_active SMALLINT NOT NULL DEFAULT 1,
  failed_login_attempts INTEGER NOT NULL DEFAULT 0,
  mfa_enabled SMALLINT NOT NULL DEFAULT 0,
  mfa_secret VARCHAR(255),
  locked_until TIMESTAMP,
  last_login_at TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS role_permissions (
  role_id BIGINT NOT NULL,
  permission_key VARCHAR(255) NOT NULL,
  PRIMARY KEY (role_id, permission_key),
  CONSTRAINT fk_role_permissions_role
    FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS api_accounts (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT,
  cpf VARCHAR(255) NOT NULL,
  company_code VARCHAR(255) NOT NULL,
  account_user VARCHAR(255) NOT NULL,
  dealer_code VARCHAR(255) NOT NULL,
  account_password VARCHAR(255) NOT NULL,
  token VARCHAR(255),
  b3_token VARCHAR(255),
  last_request_at TIMESTAMP NOT NULL,
  cooldown_until TIMESTAMP,
  in_flight INTEGER DEFAULT 0,
  error_401_count INTEGER DEFAULT 0,
  error_429_count INTEGER DEFAULT 0,
  blocked_until TIMESTAMP,
  priority_score DOUBLE PRECISION DEFAULT 0,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  CONSTRAINT fk_api_accounts_user
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS vendor_identity_map (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT,
  cpf VARCHAR(32),
  seller_name VARCHAR(255) NOT NULL,
  branch VARCHAR(64),
  source VARCHAR(32) NOT NULL DEFAULT 'legacy',
  is_active SMALLINT NOT NULL DEFAULT 1,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  CONSTRAINT fk_vendor_identity_user
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS requests (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  requester_user_id BIGINT,
  vendor_identity_id BIGINT,
  api_account_id BIGINT,
  requested_at TIMESTAMP,
  branch VARCHAR(255),
  seller_name VARCHAR(255),
  cpf VARCHAR(32),
  model_name VARCHAR(255),
  licensed VARCHAR(255),
  installments INTEGER,
  bid_percent DOUBLE PRECISION,
  with_restriction VARCHAR(16),
  group_code INTEGER,
  notes TEXT,
  requested_quota_id BIGINT,
  served_group BIGINT,
  quota_rd VARCHAR(32),
  served_at TIMESTAMP,
  status VARCHAR(64),
  contemplation_bid VARCHAR(64),
  requested_date DATE,
  requested_time TIME,
  served_date DATE,
  served_time TIME,
  CONSTRAINT fk_requests_requester_user FOREIGN KEY (requester_user_id) REFERENCES users(id),
  CONSTRAINT fk_requests_vendor_identity FOREIGN KEY (vendor_identity_id) REFERENCES vendor_identity_map(id),
  CONSTRAINT fk_requests_api_account FOREIGN KEY (api_account_id) REFERENCES api_accounts(id)
);

CREATE TABLE IF NOT EXISTS reservations (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  request_id BIGINT,
  reserved_by VARCHAR(255) NOT NULL,
  person_document VARCHAR(255) NOT NULL,
  group_code VARCHAR(255) NOT NULL,
  quota_rd VARCHAR(255) NOT NULL,
  model_name VARCHAR(255) NOT NULL,
  replacement_quota_id VARCHAR(255) NOT NULL,
  created_at TIMESTAMP,
  CONSTRAINT fk_reservations_request FOREIGN KEY (request_id) REFERENCES requests(id)
);

CREATE TABLE IF NOT EXISTS available_group_ids (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  group_api_id INTEGER NOT NULL,
  products VARCHAR(255) NOT NULL,
  due_day INTEGER NOT NULL,
  term_months INTEGER NOT NULL,
  group_kind VARCHAR(255) NOT NULL,
  group_code INTEGER NOT NULL,
  quota INTEGER NOT NULL,
  r INTEGER NOT NULL,
  d INTEGER NOT NULL,
  booked INTEGER NOT NULL,
  created_at TIMESTAMP,
  participants INTEGER NOT NULL,
  failed INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS models (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  model_api_id INTEGER NOT NULL,
  model_name VARCHAR(255) NOT NULL,
  status VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS products (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  product_api_id INTEGER NOT NULL,
  products VARCHAR(255) NOT NULL,
  status VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS active_groups (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  group_code INTEGER NOT NULL,
  due_day INTEGER NOT NULL,
  participants_count INTEGER,
  first_assembly_date DATE,
  plan VARCHAR(64),
  term_months INTEGER,
  group_type VARCHAR(16),
  models TEXT,
  status VARCHAR(32) NOT NULL DEFAULT 'is_active',
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS holidays (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  holiday_date DATE NOT NULL,
  description VARCHAR(255) NOT NULL,
  holiday_type VARCHAR(32) NOT NULL DEFAULT 'Nacional',
  is_active SMALLINT NOT NULL DEFAULT 1,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS assemblies (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  quota_rd VARCHAR(32),
  contemplation_date TIMESTAMP,
  contemplation_type VARCHAR(255),
  disqualification_date TIMESTAMP,
  client_name VARCHAR(255),
  bid_percent DOUBLE PRECISION,
  seller_name VARCHAR(255),
  group_code INTEGER,
  federal_lottery INTEGER
);

CREATE TABLE IF NOT EXISTS manual_notifications (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  request_id BIGINT,
  cpf VARCHAR(32),
  seller_name VARCHAR(255),
  branch VARCHAR(64),
  channel VARCHAR(32) NOT NULL DEFAULT 'whatsapp',
  message TEXT NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'pendente',
  copied_at TIMESTAMP,
  sent_at TIMESTAMP,
  action_user VARCHAR(255),
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  CONSTRAINT fk_manual_notifications_request FOREIGN KEY (request_id) REFERENCES requests(id)
);

CREATE TABLE IF NOT EXISTS audit_log (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  username VARCHAR(255) NOT NULL,
  action VARCHAR(100) NOT NULL,
  entity VARCHAR(100),
  entity_id VARCHAR(100),
  before_state TEXT,
  after_state TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS app_sessions (
  token VARCHAR(64) PRIMARY KEY,
  user_id BIGINT NOT NULL,
  username VARCHAR(255) NOT NULL,
  full_name VARCHAR(255) NOT NULL,
  cpf VARCHAR(32),
  branch VARCHAR(64),
  role VARCHAR(64) NOT NULL,
  permissions TEXT,
  authenticated_at TIMESTAMP NOT NULL,
  CONSTRAINT fk_app_sessions_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_appuser_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_appuser_cpf ON users(cpf);
CREATE INDEX IF NOT EXISTS idx_appuser_filial ON users(branch);
CREATE INDEX IF NOT EXISTS idx_appuser_supervisor ON users(supervisor);
CREATE INDEX IF NOT EXISTS idx_appuser_manager ON users(manager);
CREATE INDEX IF NOT EXISTS idx_appuser_role ON users(role);
CREATE INDEX IF NOT EXISTS idx_gruposativos_grupo ON active_groups(group_code);
CREATE INDEX IF NOT EXISTS idx_gruposativos_vencimento ON active_groups(due_day);
CREATE INDEX IF NOT EXISTS idx_gruposativos_status ON active_groups(status);
CREATE UNIQUE INDEX IF NOT EXISTS idx_feriados_data_tipo ON holidays(holiday_date, holiday_type);
CREATE INDEX IF NOT EXISTS idx_feriados_ativo ON holidays(is_active);
CREATE INDEX IF NOT EXISTS idx_msgnotif_status_created ON manual_notifications(status, created_at);
CREATE INDEX IF NOT EXISTS idx_msgnotif_request ON manual_notifications(request_id);
CREATE INDEX IF NOT EXISTS idx_msgnotif_cpf ON manual_notifications(cpf);
CREATE INDEX IF NOT EXISTS idx_api_accounts_user ON api_accounts(user_id);
CREATE INDEX IF NOT EXISTS idx_vendor_identity_user ON vendor_identity_map(user_id);
CREATE INDEX IF NOT EXISTS idx_vendor_identity_cpf ON vendor_identity_map(cpf);
CREATE INDEX IF NOT EXISTS idx_requests_requester ON requests(requester_user_id);
CREATE INDEX IF NOT EXISTS idx_requests_vendor_identity ON requests(vendor_identity_id);
CREATE INDEX IF NOT EXISTS idx_requests_api_account ON requests(api_account_id);
CREATE INDEX IF NOT EXISTS idx_reservations_request ON reservations(request_id);

COMMIT;
